-- CreateEnum
CREATE TYPE "ModelLifecycleStatus" AS ENUM ('ACTIVE', 'IN_PROGRESS', 'PAUSED');

-- AlterTable
ALTER TABLE "Model" ADD COLUMN     "agencyCommissionPercent" DOUBLE PRECISION,
ADD COLUMN     "birthDate" TIMESTAMP(3),
ADD COLUMN     "chatterAssignedName" TEXT,
ADD COLUMN     "contractStatus" "ModelLifecycleStatus",
ADD COLUMN     "contractUrl" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "directEmail" TEXT,
ADD COLUMN     "editorAssignedName" TEXT,
ADD COLUMN     "generalNotes" TEXT,
ADD COLUMN     "importantNotes" TEXT,
ADD COLUMN     "legalDocumentsUrl" TEXT,
ADD COLUMN     "legalName" TEXT,
ADD COLUMN     "managerName" TEXT,
ADD COLUMN     "modelPercent" DOUBLE PRECISION,
ADD COLUMN     "nextImportantDate" TIMESTAMP(3),
ADD COLUMN     "nextTask" TEXT,
ADD COLUMN     "onboardingCompleted" BOOLEAN,
ADD COLUMN     "onboardingStartDate" TIMESTAMP(3),
ADD COLUMN     "paidAmountHistoric" DOUBLE PRECISION,
ADD COLUMN     "paymentMethod" TEXT,
ADD COLUMN     "pendingAmount" DOUBLE PRECISION,
ADD COLUMN     "personalEmail" TEXT,
ADD COLUMN     "personalPhone" TEXT,
ADD COLUMN     "relationshipStatus" "ModelLifecycleStatus",
ADD COLUMN     "scripterAssignedName" TEXT,
ADD COLUMN     "stageName" TEXT,
ADD COLUMN     "telegramHandle" TEXT,
ADD COLUMN     "vipChannelRef" TEXT,
ADD COLUMN     "whatsapp" TEXT,
ADD COLUMN     "workGroupRef" TEXT;
